version: '3.5'

services:
  nginx:
      build: ./nginx
      container_name: nginx
      ports:
        - "80:80"
      volumes:
#        - ./nginx/vhost:/etc/nginx/conf/vhost:ro
        - /Users/:/Users/
        - /Volumes/:/Volumes/
        - ./nginx/vhost:/Volumes/work/vhost:ro
      environment:
          - DEBUG=true
          - HOST_OS=mac
#      expose:
#        - "9000"
#        - "6379"
#        - "3306"
#        - "9200"
#        - "9300"
      extra_hosts:
            - "a.net:127.0.0.1"
            - "b.net:127.0.0.1"
      networks:
              swoole:
                  aliases:
                    - nginx
              swoole-h:
                  ipv4_address: 10.3.1.100
                  aliases:
                    - nginx
      depends_on:
            - php
  php:
      build: ./php
      container_name: php
      expose:
        - "9000"
      volumes:
        - /Users/:/Users/
        - /Volumes/:/Volumes/
        - /tmp/:/tmp/
      extra_hosts:
        - "a.net:10.3.1.100"
        - "b.net:10.3.1.100"
      networks:
              swoole:
                  aliases:
                    - php
              swoole-h:
                  ipv4_address: 10.3.1.110
                  aliases:
                    - php
      depends_on:
            - mysql
  phpcli:
      build: ./php-cli
      container_name: php-cli
      command: php /demo/demo.php
#      expose:
#        - "9501"
#      ports:
#        - "9501:9501"
      extra_hosts:
      - "a.net:10.3.1.100"
      - "b.net:10.3.1.100"
      volumes:
        - /Users/:/Users/
        - /Volumes/:/Volumes/
        - ./php-cli/demo:/demo:ro
        - /tmp/:/tmp/
      #working_dir: /Volumes/
      networks:
              swoole:
                  aliases:
                    - phpcli
              swoole-h:
                  ipv4_address: 10.3.1.120
                  aliases:
                  - phpcli
  mysql:
      build: ./mysql
      container_name: mysql
      hostname: mysql
      ports:
        - "3306:3306"
      environment:
        MYSQL_ROOT_PASSWORD: root
      volumes:
        - /tmp/:/tmp/
        #- /my/own/datadir:/var/lib/mysql
      networks:
                  swoole:
                      aliases:
                        - mysql
                  swoole-h:
                    ipv4_address: 10.3.1.200
                    aliases:
                    - mysql
  adminer:
    image: adminer
    container_name: adminer
    #restart: always
    ports:
    - 3300:8080
    networks:
      swoole:
        aliases:
        - adminer
  redis:
      build: ./redis
      container_name: redis
      #command: redis-server /usr/local/etc/redis/redis.conf
      ports:
        - "6379:6379"
      volumes:
        - /Users/:/Users/
        #- ./redis/conf/redis.conf:/usr/local/etc/redis/redis.conf
      networks:
                  swoole:
                      aliases:
                        - redis
networks:
  swoole:
    name: swoole
    driver: bridge
  swoole-h:
    name: swoole-h
    driver: macvlan
    ipam:
      driver: default
      config:
        - subnet: 10.3.1.0/24